// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdexwpcnXB5DcXD2OWr1DvJiGJWg1J670',
    appId: '1:920059298210:web:c432a39a2e49c7857a72fb',
    messagingSenderId: '920059298210',
    projectId: 'studdy-buddy-a6112',
    authDomain: 'studdy-buddy-a6112.firebaseapp.com',
    storageBucket: 'studdy-buddy-a6112.appspot.com',
    measurementId: 'G-QJ1WPPD77E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx9KIa-QiFKRHYqB9aOejNf-9B0nF-5HE',
    appId: '1:920059298210:android:ccdea5e1514bd22f7a72fb',
    messagingSenderId: '920059298210',
    projectId: 'studdy-buddy-a6112',
    storageBucket: 'studdy-buddy-a6112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYYl_gOD766sGHbD8XNbzySiIi44fGww',
    appId: '1:920059298210:ios:4a981a3f6fe020b17a72fb',
    messagingSenderId: '920059298210',
    projectId: 'studdy-buddy-a6112',
    storageBucket: 'studdy-buddy-a6112.appspot.com',
    iosBundleId: 'com.example.studyBuddy',
  );
}
